server:
  port: ${SERVER_PORT:8080}

# Database Properties
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cdn?useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Hibernate Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    #Colocar aqui o endereço de contigência para armazenar os arquivos.
